### ISSUE TITLE
Bugs when I add a slot that from 8:00am to 9:00am

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T08-3/main#175] opened 2019-04-04 13:38 UTC
**Describe the bug**
When I type the command “add n/CS2113T Tutorial d/mon st/08:00am et/09:00am des/Topic: Sequence Diagram t/CS2113T t/Tutorial r/normal”. It shows it is an invalid command format. 

**Expected behavior**
It should be added successfully because the instruction shows it is a valid format. 
**Screenshots**
![image](https://user-images.githubusercontent.com/32561507/55454402-68d99200-5612-11e9-977c-052078dfa58f.png)

<hr>

**Reported by:** @wanchunwei
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#177]</sub>

**Comment by seanieyap** [comment] 2019-04-04 17:58
Hi,

Thank you for your feedback. This is actually not a bug bug miss-phrased documentation, actually with the 0 appended to a 12-hour format time, we determined that it would be erroneous to consider that 12-hour format since that is not actually how the format works. But in light of this, this case will be added to the parsing system as well; this will provide a greater user experience and ease of use. This will be fixed soon !

**Comment by seanieyap** [comment] 2019-04-04 19:55
This bug has been fixed.

**Closed as completed by seanieyap** 2019-04-04 19:55 UTC
Labels: type.Bug, status.Ongoing, priority.High, severity.Low, severity.Medium
